import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { ThemeProvider, UserContext } from "../context/user.context";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils";
const inter = Inter({ subsets: ["latin"] });
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${cn(
      "min-h-screen bg-background font-sans antialiased",
      fontSans.variable
    )} " bg-slate-800  dark "   `}>

      <body className={inter.className }>
        <UserContext>
        <Navbar />
          {children}
          </UserContext>
            
        </body>
    </html>
  );
}
